### PR TITLE
Page button

### PR DESCRIPTION
**Pull request by hsnice16**
implemented Button page.
Live:  https://poshui-documentation-button.netlify.app/pages/button.html

### CODE REVIEW

**Comment by Vishnu-Aithal** [comment]
Looks Good
Would be nice to have a Copy Button to copy Html Template to clipboard

**Review by foolhardy21 — APPROVED** [review]
LGTM.

**Review by foolhardy21 — APPROVED** [review]
LGTM.

**Comment by yash9263** [comment]
looks good to me

**Review by b0llu — APPROVED** [review]
Great work with the buttons!

**Comment by hsnice16** [comment]
@Vishnu-Aithal I have also thought of that. I will look to add after first submission. But, thanks for pointing this.

**Pull request merged**
