### PR TITLE
add badge page

### PR DESCRIPTION
**Pull request by hsnice16**
implemented badge page.
Live: https://poshui-documentation-badge.netlify.app/pages/badge.html

### CODE REVIEW

**Review by vrx29 — APPROVED** [review]
looks good to me nice UI for badges

**Review by vrinda-mahajan — APPROVED** [review]
Good to merge.👍

**Comment by hsnice16** [comment]
Thank you for reviewing.

**Comment by vashnavichauhan1825** [comment]
you can also add more social media presence like twitter , linkedin.

**Pull request merged**
