### PR TITLE
add feature responsiveness

### PR DESCRIPTION
**Pull request by hsnice16**
added responsiveness.
Live: https://poshui-documentation.netlify.app/

### CODE REVIEW

**Review by Hamza-777 — APPROVED** [review]
Looks responsive but just remove the left padding or margin whatever it is in the code-preview in the mobile screen so that you don't have to start by scrolling to the right to see the code.

**Comment by hsnice16** [comment]
I was looking how I can do that but as inside `<code>` it applies the spacing present in the source code. So it is not coming because of any margin and padding. 

And thanks for reviewing.

**Review by ParthParolekar — APPROVED** [review]
Center the logo and navbar on mobile screen. Everything else looks great.

**Comment by hsnice16** [comment]
@ParthParolekar 

Are you saying to do this?

image

But, Does it look good?

I think this is fine, 

image

**Review by BalajiHarinath — APPROVED** [review]
Looks good to me.

**Comment by ParthParolekar** [comment]
> @ParthParolekar
> 
> Are you saying to do this?
> 
> image
> 
> But, Does it look good?
> 
> I think this is fine,
> 
> image

The first one looks good to me but it is your choice. Maybe ask others for their input as well.

**Comment by hsnice16** [comment]
Oh! okay. I like second one 😅. @Hamza-777 and @BalajiHarinath, guys Can you give your input?

**Comment by BalajiHarinath** [comment]
> Oh! okay. I like second one 😅. @Hamza-777 and @BalajiHarinath, guys Can you give your input?

For me both the variants of the nav bar looks good😀. It's more of a personal choice I suppose.

**Comment by Hamza-777** [comment]
> Oh! okay. I like second one 😅. @Hamza-777 and @BalajiHarinath, guys Can you give your input?

Yeah looks good both ways upto you now how you prefer it.

**Pull request merged**
