### PR TITLE
add Introduction Page

### PR DESCRIPTION
**Pull request by hsnice16**
implemented Introduction Page.

Live: https://poshui-documentation-introduction.netlify.app/pages/introduction.html

p.s. - Alert and Home are also working

### CODE REVIEW

**Review by partha8 — APPROVED** [review]
LGTM, but you should change the colors in highlightsjs. The contrast can be improved b/w the background and the text.

**Comment by Hamza-777** [comment]
Some real posh work there in PoshUI Himanshu and what partha said about the color contrast!!

**Comment by hsnice16** [comment]
Thanks @partha8 and @Hamza-777 to review it. I will look into the contrast thing. Thanks for pointing this out.

**Comment by hsnice16** [comment]
@partha8 Can you suggest something? As I tried to bold the text But It is not looking good.

**Comment by Hamza-777** [comment]
Looks good to me. Just try to lighten the background color in the code area. That will definitely make it look better for example #ccc or #eee.

**Comment by partha8** [comment]
> @partha8 Can you suggest something? As I tried to bold the text But It is not looking good.

@hsnice16 This looks good too, to be honest. But you can also try using a very light grey shade in the background or use an already available theme.

**Comment by hsnice16** [comment]
Actually, as the background has a light slate color, the default theme (or light grey, or #ccc or #eee) is not looking good.

But, thanks pointing this out. 
I am merging it.

**Pull request merged**
